language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ow2V2kiNfRMYtc+HiRofA3sVTXZzeIz36Oq2SSHCSE1mquF6eAdlrykUrwPQksLpz8Ot57FeISb8IyRNxUP/UyugLjZb008+hvPBbPc+q3GBs5JssPEAN/MTqDHyjSeUOxVfLwkpmXzOGQJKl5t7gtXoGZUOpLb7+bO8JApA20289WnrarI1I7id1PvUEtPbN3Ag402WWNmWd8TCP3EVu5Q8qEKLOOxkhc7x7ocWYkeX8E9dlBa8oUi2c2dcpeiVDnHgE/5aDRAVF4C7cGf49he7eTAgTMGnP9q869ds1TFBNBzYb/jXVX1M7KCeXRPr1KvayRGMxGnEPjSLQZt/YfylXjl6/g7SYNBP5clb9R995nB9MW9evJi6vLDLuRLv4bZw74Z51SCslZozRMQqPpCSkPlmJ6y0/BVs2RI91PgQ/NQRpNLzd7L2MkT0lIr/KmZHOkg+UyCJzuLBp12QKyvr8fuxWybXJpQ23BBpde9Bb6EeVU2bbBFJApL1xpDiFpnx0ZbObdqPR2NkaGIbvNPKgjJvskrfWsAPwrn55KkB9lebcC5UPs5dzJcUJG3XYzvx/ig+wRNSST+Shg2DkMUI0cYzj5uEaadgCKvPo6uy6udwKoaeKVlVQrDOUqZlSHnLYdvt8j2AjLGmhNXuwHGlRH/rMvGmeGINXmxGz2A=
  app: mini-steam
  on:
    repo: saniochky/mini-steam
    branch: main
  skip_cleanup: 'true'
