language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

deploy:
  provider: heroku
  api_key:
    secure: m51zwNK5DabnaT53gcXmkrd73Uqy+tLtK8o2b3TDbfNYDRPH8Utu11x8tJKtZaLWRHHsEIESdeJuK745ZAwy43lS6rwjYj9ulUxSmgEvDHkjuk5VomizH9Tgxp3Ig9BSlFzmWP2ymFQ682gKdIwfTdoJ+giieojzYGr9EDH3B1no92Fqu1ipeojtGg6MKwyreKmA4oMptl8huIafuuVa+jepAPoJgiY3hI0SxT2qfXS5DngpRzz0fgndZDuYeuyG4MBSawUh0HlFETZ1ehxdIMqHycJgn5TODS2DofciAOjSeJtgq3Zd46wv2KyMnCYBLTWv8NontWjL8o9b2XoNVGZWG1AIzpRTCRH4ZtfYgmWg8oef1HRW+Z4XsmJiO2Jzg8i9JceGmjLOKzXmcwnk8O3CNNLtXi/+0Ln1JjhOlyME2XA7SJN/zLb40jdUcO/0WdYl4MXNFIz+gxvAXXmQsxWBOT7er+KE9I1ENg08KS2QDq3iZf3o0xcdp/Y1mEZEI57hXS77uo3dAJDo5pcXZqnDesKcQy2Yro0vupjuFbBFfLQTX70v1BPOOocR3Y7kGttyAg9GKu/ytLjDR444uS73IlU1fEmFZJ5TuX9iY9SlxXBMyItf+1JXoxzdKlfLBMVgPX3JqqLH0Br3op8aaA7HbE5o6Vd+EW7yB73bdmA=
  app: mini--steam
  on:
    repo: saniochky/mini-steam
    branch: main
  skip_cleanup: 'true'
